### ISSUE TITLE
Strand interpretation

### ISSUE THREAD

**Issue by luigra** [kensung-lab/SurVirus#1]
Dear authors, 

I am using SurVirus to analyse some sequencing analysis and I want to be sure I am correctly interpreting the strand results.

In my specific case I am obtaining as result (in the results.remapped.t1.txt file)  :
ID=0 scaffold_0:-112418650 CelTag:+716 SUPPORTING_PAIRS=16 SPLIT_READS=7 HOST_PBS=0.907751 COVERAGE=0.654667 

Does it mean that in the I should expect in the scaffold_0 upstream the Integration sites a value higher than 112418650 and for the CelTag downstream the integration site a value higher than 716 ? 

Is this compatible with the interval reported in the results.txt file? 
0 scaffold_0:-:112418650:112419141 CelTag:+:92:716 19 14 7 1817 0.884165 0.924575 0 0 0.657333 0.652000 

Thanks in advance for any help

**Comment by Mesh89** [comment]
Hi,

+ means that the breakpoint is on the positive strand (5-to-3'), while - is the negative strand.
In your case, it means that in your sample the sequence downstream of scaffold_0:112418650 is adjacent to the sequence upstream of CelTag:716.
So the junction would look like this:

-----------||-----------------
CelTag 716  112418650 Scaffold_0

results.txt is an intermediate file, results.remapped.t1.txt is the refined and filtered version which we recommend using.

Let me know if you have any more questions.
Ramesh

**Comment by luigra** [comment]
Thank you so much Ramesh,

is the tool giving any information of the relative orientation of  CelTag and Scaffold_0? 
In other words I should expext CelTag 200-716 -> Scaffold_0 112418650 - 112418750 or   CelTag 900-716 -> Scaffold_0 112418650 - 112418750 ?

**Comment by Mesh89** [comment]
Basically (using your numbers) CelTag:+716 would mean CelTag:200-716 is part of the junction sequence. CelTag:-716 would mean that CelTag:716-900 is part of the junction sequence. Same for Scaffold_0.

So in your case CelTag 200-716 -> Scaffold_0 112418650 - 112418750 is correct.

**Comment by luigra** [comment]
Thanks a lot for your clarification, 

It seems to me that the tool has some problem in capturing the right orientation: for a benchmark comparison with other tools I simulated some integrations of a plasmid in a scaffold with either scaffold and plasmid in the same orientations and SurVirus always (108 experiments) detects opposite orientation. Please let me know if you need these datasets. 

Best wishes
Luigi

**Comment by Mesh89** [comment]
Hi,

In the same orientation meaning that you inserted the plasmid into the host genome as it appears in the reference? (i.e. without reverse-complementing it)

What orientation does the tool give?

**Comment by luigra** [comment]
Hi Ramesh,

I gave another look at the results I obtained with simulated data and they look correct, by using your suggestion in the previous comment for interpreting them. 

Sorry for any confusion
