### ISSUE TITLE
An unexpected termination of the Survirus program

### ISSUE THREAD

**Issue by ssliquid** [kensung-lab/SurVirus#10]
Hello, Thank you very much for the program you wrote and the program solves a difficult problem in my scientific research. However, in each sample, my program has stopped running at this point:

 CMD: bwa mem -t 1 -h 1000 /mnt/hgfs/LINuXshare/host/host.fa /mnt/hgfs/LINuXshare/result/host_bp_seqs.fa
[main] Real time: 12.952 sec; CPU: 3.414 sec
[E::idx_find_and_load] Could not retrieve index file for '/mnt/hgfs/LINuXshare/result/host_bp_seqs.bam'

However, there are  "host_bp_seqs. bam"  file  and "results.remapped.t1.txt" file existing in the working directory (result). It's kind of weird. Was the  the program finished? 
Thank you!

**Comment by ssliquid** [comment]
Oh, i have found the same issule and it's only maybe a warning. Haha : )

**Comment by Mesh89** [comment]
Yes. It is a pointless but harmless warning recent versions of pysam issue. The program finished without an issue.
