### ISSUE TITLE
Unwanted character appears in my command

### ISSUE THREAD

**Issue by dasiav7** [kensung-lab/SurVirus#11]
Hi,

Thank you for this great application. 
I recently encountered two problems with SurVirus: 

1. Python problem: 'Do you mean print("Executing:", cmd)', This might happen because of the version of Python, I already modified your code .
2. There will be an unwanted "b" adding on my input file name. I wonder why this will happen?

![image](https://user-images.githubusercontent.com/24263046/133536140-73a5b3c4-49e0-4366-ac54-659a9746a595.png)

Thank you!

**Comment by Mesh89** [comment]
Hi,

Would it be possible for you to execute the software with Python2? 
You are likely using 3, and the software was written for 2.

As for the b, I have never encountered it, but it seems like the bam filename is in bytes and not a str (string).
https://newbedev.com/what-does-a-b-prefix-before-a-python-string-mean

Does the program finish correctly?

**Comment by dasiav7** [comment]
Hi,

Thank you so much for your quick response. I didn't wait until it finished. I'll try python2 first to see what will happen. I'll report you the consequence.

**Comment by dasiav7** [comment]
> Hi,
> 
> Would it be possible for you to execute the software with Python2?
> You are likely using 3, and the software was written for 2.
> 
> As for the b, I have never encountered it, but it seems like the bam filename is in bytes and not a str (string).
> https://newbedev.com/what-does-a-b-prefix-before-a-python-string-mean
> 
> Does the program finish correctly?

**Comment by dasiav7** [comment]
> Hi,
> 
> Would it be possible for you to execute the software with Python2?
> You are likely using 3, and the software was written for 2.
> 
> As for the b, I have never encountered it, but it seems like the bam filename is in bytes and not a str (string).
> https://newbedev.com/what-does-a-b-prefix-before-a-python-string-mean
> 
> Does the program finish correctly?

I changed to use Python 2.7 then it works now. Thank you.!

**Comment by dasiav7** [comment]
I encountered another problem:

![image](https://user-images.githubusercontent.com/24263046/133630223-6a676d0a-4ec8-4c83-b9d1-9fff0b75e459.png)


The program does not contain "samtools index host_bp_seqs.bam". You may need to update this. Thank you.

**Comment by dasiav7** [comment]
> Hi,
> 
> Would it be possible for you to execute the software with Python2?
> You are likely using 3, and the software was written for 2.
> 
> As for the b, I have never encountered it, but it seems like the bam filename is in bytes and not a str (string).
> https://newbedev.com/what-does-a-b-prefix-before-a-python-string-mean
> 
> Does the program finish correctly?

I encountered another problem: it seems that the program does not contain the code 'samtools index host_bp_seqs.bam'.
You may want to update this .

![image](https://user-images.githubusercontent.com/24263046/133708802-46eaf3b8-5d59-4679-8c2c-61a8bd7d49b0.png)

**Comment by Mesh89** [comment]
This is just a meaningless warning that recent versions pysam issues. You can safely ignore. See also 

https://github.com/kensung-lab/SurVirus/issues/6
https://github.com/kensung-lab/SurVirus/issues/10

**Comment by dasiav7** [comment]
Oh, okay I see. I found the result is empty and thought it might be the consequence of this issue. Now I get it. Thanks a lot!

**Comment by dasiav7** [comment]
Hi,

Everything's fine and I got the final output. Thank you! I now have a couple of questions about the result file. What does "PAIRED WITH ID=" mean in the results.remapped.t1.txt? Why is HOST_PBS larger than 0? Can I directly use the number of "supporting pairs" or "split reads" as the quantity of viral integration to do further statistical analysis?  Furthermore, I can directly use results.remapped.t1.txt, right, because it has been filtered?

Thank you so much,
Joy

**Comment by Mesh89** [comment]
Hi,

PAIRED WITH ID= means that the two breakpoints form a pair. This indicates that together they *may* form an integration.
I think you can use split reads pretty much directly. That is the number of reads covering the breakpoint. 
Supporting pairs is a bit more difficult to use as it depends on the insert size distribution as well. If your dataset has longer pairs then you will find more supporting pairs.
Yes, you may use the t1 (tier 1) results. The unfiltered results are in the file without the t1 suffix.

**Comment by dasiav7** [comment]
Hi,

Thank you. So, what's the difference between the paired breakpoints and the others?

**Comment by Mesh89** [comment]
Paired breakpoints have a "mate" breakpoint, and together they may form a virus integration into the host.
Unpaired breakpoints do not have a mate breakpoint.
