### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by luigra** [kensung-lab/SurVirus#2]
Dear authors,

I created a Singularity container using ubuntu 18.03 and installing python-numpy, python-pyfaidx, python-pysam, bwa (0.7.17), Sdust, samtools (1.10), bedtools (2.29.2) and SurVirus. 

I used SurVirus to analyse several datasets and it worked without any problem but on a specific dataset (Downloaded from SRA SRR619716) I am always getting segmentation fault either when I submit the job on the cluster with qsub and when I run it on the local nodes (see enclosed error File):
[20210205_SurVirus.err.txt](https://github.com/kensung-lab/SurVirus/files/5990140/20210205_SurVirus.err.txt)

The program creates the file results.remapped.txt (enclosed)
[results.txt](https://github.com/kensung-lab/SurVirus/files/5990165/results.txt)

but the results.remapped.t1.txt file is empty. 

Is there any dependence I did not correctly install or anything wrong I am doing in running the program?

python /usr/share/SurVirus-master/surveyor.py --threads 24 --bwa /usr/bin/bwa --samtools /usr/bin/samtools --bedtools /usr/bin/bedtools --dust /usr/bin/sdust ${reads[0]},${reads[1]} ${outdir} ${bwaseq3} ${bwaseq1} ${bwaseq2} --fq

Thanks in advance for your help

**Comment by Mesh89** [comment]
Can I confirm that you are using hg38 as your host genome? Are the virus genomes you are using publicly available?

**Comment by luigra** [comment]
Hi Ramesh ,

I am using hg38,  Ensembl version 94 downloaded from ftp://ftp.ensembl.org/pub/release-94/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz and the virus genome is NC_003977.2 Hepatitis B virus downloaded from NCBI.

Thanks in advance

**Comment by Mesh89** [comment]
Hi,

It should be fixed in the latest commit. Please let me know if you still encounter the problem.
