### ISSUE TITLE
pysam samtools error

### ISSUE THREAD

**Issue by anagradissimo** [kensung-lab/SurVirus#3]
Dear authors,

I've been trying to run SurVirus on HPC cluster. All tools were installed in gcc.7.1.0

I keep having an error that I think it would be an incompatibility between pysam and samtools (see file attached):

[samtools_error_SurVirus.txt](https://github.com/kensung-lab/SurVirus/files/6086003/samtools_error_SurVirus.txt)

Tool versions installed are as follows:
module load python/2.7.15/gcc.7.1.0
module load samtools/1.10/gcc.7.1.0
module load bedtools2/2.28.0/gcc.7.1.0
module load bwa/0.7.17/gcc.7.1.0
module load sdust/0.1/gcc.7.1.0
module load SurVirus/022221/gcc.7.1.0

I only need to load SurVirus, which automatically loads all the other tools. 

My command is:
python $(which surveyor.py) --fq ./cell_lines/HeLa_2G0057_R1.fq,./cell_lines/HeLa_2G0057_R2.fq ./output/ ./host/2_host.fa ./virus/2_virus.fasta ./host+virus/host+virus.fasta

I don't mention the other flags for bwa, samtools, or sdust, since they are being previously loaded.

The script keeps aborting with the same error, what can I do to run the program properly?

Also, I noticed that the output 'head_1.fq' being generated only has 100,000 sequences (and my fastq files have > 500,000 reads); is it because the program is doing subsampling? Or not enough memory?

Thank you.

**Comment by Mesh89** [comment]
For head_1.fq, this is normal, it is not due to memory.

As for your problem, can you try the latest version?
