### ISSUE TITLE
[E::idx_find_and_load] Could not retrieve index file for '/work/host_bp_seqs.bam'

### ISSUE THREAD

**Issue by sujunhao** [kensung-lab/SurVirus#6]
Hi, I tested several BAM files on SurVirus (trying to find  human and lentivirus integration), it runs smoothly first, but all got the same errors like:

E::idx_find_and_load] Could not retrieve index file for '/work/host_bp_seqs.bam', which is in the "Finding alternative locations..."step i think.

it means SurVirus can not find the index file for one of the programs generated file 'host_bp_seqs.bam'
any hint to solve this problem, and is there a way to the reason for this error?

Thanks

Junhao

**Comment by Mesh89** [comment]
Hi,

I will look into it. I believe the results should have been generated anyway, am I right?

**Comment by sujunhao** [comment]
Hi, 
Yes, I can find the results file, but the finnal 'results.remapped.t1.txt' is empty in my case.
and i found this index error problem can be solved by sort and index the 'host_bp_seqs.bam' file.

**Comment by Mesh89** [comment]
That step comes after generating results.remapped.t1.txt , so the file being empty is unrelated, it means SurVirus did not find any confident breakpoint.

I will fix the indexing issue and get back to you.

**Comment by Mesh89** [comment]
Hi,

After further investigating, it looks like it is just a warning that recent pysam versions output. It can safely be ignored.
