### ISSUE TITLE
The viral sequence integrated into the host genome

### ISSUE THREAD

**Issue by lananhle** [kensung-lab/SurVirus#8]
Thanks for making such a helpful tool. I would like to find out the virus sequences that integrated into host genome. However, I can just identify the sites of virus integration in the file named results.remapped.t1.txt. 
Can you tell me which part of output files show this.   

Thank you very much

**Comment by Mesh89** [comment]
Hi,
Would it be possible for you to provide an example line from your results.remapped.t1.txt? You may change the numbers/chr names if it is private information.

**Comment by lananhle** [comment]
@Mesh89 hello,

Here is my output:

`ID=0 17:-22245496 AB014381.1:-1473 SUPPORTING_PAIRS=86 SPLIT_READS=0 HOST_PBS=0.993751 COVERAGE=0.636194`
`ID=3 GL000220.1:+153987 AB014381.1:-1825 SUPPORTING_PAIRS=115 SPLIT_READS=77 HOST_PBS=0.951973 COVERAGE=0.763993`
`ID=5 11:+51578725 AB014381.1:-1500 SUPPORTING_PAIRS=67 SPLIT_READS=0 HOST_PBS=0.988277 COVERAGE=0.453358`

Thank you a lot!

**Comment by Mesh89** [comment]
The second column is the host side of the breakpoints (contig names are "17", "GL000220.1" and "11").
SurVirus output is not limited to integrations, but detects breakends/junctions between the host genome and a virus genome. For an integration, you would normally want two breakends that are close on the host but have opposite strand.
You may want to read https://github.com/kensung-lab/SurVirus/issues/1 for more information on the output interpretation.

**Comment by lananhle** [comment]
Hello Mesh89,

Thank you for your reply.
According to thread #1, I revised my file named "results.txt" and the junction structure of ID=3 and ID=5 were:
---------------------------------||-----------------------------
GL000220.1:+:153601:153987 || AB014381.1:-:1825:2255

---------------------------------||-----------------------------
11:+:51578573:51578725        || AB014381.1:-:1500:1832

However, I can't draw junction in the case of ID=0 as the orientation of both host and virus are negative strand. Can you explain this case?
And, In case of ID=0, the split reads didn't found.  I wonder how SurVirus identified the breakpoint. Can I get bam file with candidate mapping read (soft-clipped read pairs and discordant read pairs) in SurVirus workflow.

Thank you so much!

**Comment by Mesh89** [comment]
The breakpoint strand actually mirrors the strand the reads supporting the breakpoint aligned to. 
If there is a +, the reads supporting that breakpoint aligned to the positive strand in the virus and/or the host. Similarly, if there is a -, the reads aligned to the negative strand.
For ID=0, both of the set of reads aligned to the negative strand. This may happen if for example the virus sequence is reverse complemented before the integration/junction. In our tests on HPV and HBV we found this is not uncommon.

AB014381.1:-:1600:1473 || 17:-:22245496-22245600

Regarding the split reads, I would be suspicious of highly supported breakpoints that do not have split reads. This means that after creating the junction sequence, no read aligns across the junction, i.e. it encompasses both the virus and the host sequences.
They are not necessarily false positives, but they certainly deserve more study. You should be able to find BAM files with the evidence SurVirus reports in the folder readsx in your workspace. The numbers mirror the IDs of the calls.
